### ISSUE TITLE
Name of activities

### ISSUE THREAD

**Issue by NikunjKhangwal** [zacharee/RootActivityLauncher#11]
The app doesn't show actual name of activities.
![IMG_20240330_213134](https://github.com/zacharee/RootActivityLauncher/assets/99175083/fe963ea9-e64f-4d25-8454-138179603648)

For example this is from activity launcher app:
![IMG_20240330_213148](https://github.com/zacharee/RootActivityLauncher/assets/99175083/0dc155b8-8485-485c-b6c9-e942251c49b0)

**Comment by CamsShaft** [comment]
Yes, it does. You have to open your eyes and read a bit, but it's there.

**Comment by NikunjKhangwal** [comment]
> Yes, it does. You have to open your eyes and read a bit, but it's there.

I'm talking about the header where it's showing "1DM+" for everything

**Comment by CamsShaft** [comment]
> > Yes, it does. You have to open your eyes and read a bit, but it's there.
> 
> I'm talking about the header where it's showing "1DM+" for everything

I'm sorry but I dont know what you're talking about. It has "1DM+" listed twice for one app and once for RAL.

**Comment by NikunjKhangwal** [comment]
> I'm sorry but I dont know what you're talking about. It has "1DM+" listed twice for one app and once for RAL.

These
![IMG_20240503_135954](https://github.com/zacharee/RootActivityLauncher/assets/99175083/cb0485af-cade-4c40-a6ef-495be9b0d19d)

**Comment by CamsShaft** [comment]
Like how they're not listed in activities for root activity launcher??

**Comment by NikunjKhangwal** [comment]
Yeah

**Comment by CamsShaft** [comment]
It's because you're searching for components and specified "saved" so it displayed only the component to do with the word "saved" in that app. And the name for the activity is "idm.internet.download.manager.SavedPasswords". With the information you gave me that's really all I can tell you. I don't know what else you're asking for if that's not it.

**Comment by NikunjKhangwal** [comment]
Nevermind then. I'm not good with words so the message is not going through. Have a nice day :)

**Comment by CamsShaft** [comment]
Hey, you don't have to close it. I'm really just trying to help with the information you've provided. I'm not sure if the developer checks these often so I thought I would give it a try and help you. Is there a better way to communicate for you? Perhaps a video screen-capture would help visually to understand what you're trying to get across. Even if English isn't your first language there's always translators I could use if that helps you express yourself easier. Don't just give up!

**Comment by NikunjKhangwal** [comment]
It's not about English, i might be using the terms wrong as I'm not a developer so i don't know what's the name of every component. I was using the "activity name" term wrong as well.
Anyway it's not a big deal, this was just a small suggestion and doesn't really matter if app stays the way it is. Thanks

**Comment by drogga** [comment]
Those are called Activity Labels, they are usually in the Manifest, but not all activities of all apps are with a label, but it looks like here you made a good point, maybe it's already addressed with a commit - Will find out when a new ver. comes out on PS.

**Comment by NikunjKhangwal** [comment]
Sure and thanks for clarifying

**Comment by drogga** [comment]
NP ;)
You can even edit the subject title to something like `Resolve and Show activities real labels` if you want.
