### ISSUE TITLE
Question regarding building the app

### ISSUE THREAD

**Issue by badbeing** [zacharee/RootActivityLauncher#7]
Hello, I found your app on PLay Store recentyl and noticed that you have mentioned we could clone and nuild the app via Android Studio. To be fair I am totally new on Android Dvelopment and it is only my second time using Android Studio to build APKs. However, I encountered a few errors in the Studio when trying to build.

`Unresolved reference: IPackageManager` error shows up on both Line 6 and Line 130 in the file **BaseComponentAdapter.kt** located in _RootActivityLauncher\app\src\main\java\tk\zwander\rootactivitylauncher\adapters\component\_.
Another error `Unresolved reference: USER_SYSTEM` is shown on Line 142 of the same file. 

JDK version: 19
Android Studio version: Dolphin (2021.3.1)
Kotlin plugin version: 213-1.7.10-release-for-android-studio-AS6777.52 (All of the components in Android Studio should be up to date)

May I ask what are the steps to build the app correctly? Thank you.

**Comment by badbeing** [comment]
Found the solution, a modified android.jar....

**Comment by james28909** [comment]
> Found the solution, a modified android.jar....

could you elaborate? like what do others need to do to get this done?

**Comment by badbeing** [comment]
> > Found the solution, a modified android.jar....
> 
> could you elaborate? like what do others need to do to get this done?

I viewed other repos by Zach, one of them includes the building instructions and a link to the modified jaf file he uses. I will edit this comment and put the repo as reference later as I too need to look for it again.. XD

**Comment by drogga** [comment]
@badbeing Your link looks fine, but it actually leads to `https://github.com/zacharee/RootActivityLauncher/issues/url`, please fix it. Thank You.
_(No need to quote or mention/tag me in case you reply)_

**Comment by badbeing** [comment]
Apologies for the late reply, I haven't caught up on the repo for a while now.

Here is the repo link of the said modified android jar file, feel free to use it and build the app
https://github.com/Reginer/aosp-android-jar

**Comment by drogga** [comment]
@badbeing But you still haven't edited your previous comment to fix the bad link...

Thanks for the JAR, but I can't use it because I don't have a PC RN (nor a powerful android device), I don't have/know and can't use any IDE, nor I know how to use Actions here, so it's actually not what I'm looking for.

**Comment by badbeing** [comment]
> [@badbeing](https://github.com/badbeing) But you still haven't edited your previous comment to fix the bad link...
> 
> Thanks for the JAR, but I can't use it because I don't have a PC RN (nor a powerful android device), I don't have/know and can't use any IDE, nor I know how to use Actions here, so it's actually not what I'm looking for.

Updated now, thanks for reminding

**Comment by drogga** [comment]
NP ;) & Thank You.

Maybe you can sync with the latest commits and create a new release _(not necessarily a debug build .apk)_ in your fork ?, _I don't care about the signature/certificate, you can use Test/Debug or a custom key, it doesn't matter._
